version: '3.7'

services:

  mysqldb:
    image: mysql:8.0.33-debian
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - D:\tmp\selfnurse-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=self_nurse_db
