version: '3.7'

services:
  app:
    image: selfnurse:0.0.1
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET_KEY=Ct0hqIlulr~~ecVa-z=y#Eu6.6]i]yyohPSLp!wQ2SxW'6.]_H
      - NODE_ENV=Development
      - DB_HOST=localhost
      - DB_PORT=3306
      - MYSQL_USER=root
      - DB_NAME=self_nurse_db
      - MYSQL_PASSWORD=toor
      - DB_LOGGING=false
  mysql:
    image: mysql:8.0.33-debian
    volumes:
      - D:\tmp\selfnurse-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=self_nurse_db
